// src/app/layout.tsx
/*import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import SessionWrapper from '@/components/SessionWrapper'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  )
}
*/

// src/app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import styles from './layout.module.css'
import SessionWrapper from '@/components/SessionWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sans bg-gray-100">
        {' '}
        {/* Cambia bg-gray-100 por la clase de fondo que desees */}
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  )
}
