import { OrderItemStatus } from '@prisma/client'; // Assuming OrderItemStatus enum is generated by Prisma
// import { Order } from './order'; // Placeholder
// import { ProductVariant } from './productVariant'; // Placeholder

export interface OrderItem {
  order_item_id: number;
  order_id: number;
  variant_id: number;
  quantity: number;
  unit_price: number; // Prisma Decimal
  item_total_price?: number | null; // Prisma Decimal, GENERATED ALWAYS AS in SQL
  status?: OrderItemStatus | null;
  notes?: string | null;
  // order: Order;
  // variant: ProductVariant;
}