import { OrderStatus } from '@prisma/client'; // Assuming OrderStatus enum is generated by Prisma
// import { Establishment } from './establishment'; // Placeholder
// import { User } from './user'; // Placeholder
// import { OrderItem } from './orderItem'; // Placeholder
// import { OrderStatusHistory } from './orderStatusHistory'; // Placeholder

export interface Order {
  order_id: number;
  establishment_id: number;
  client_user_id?: number | null;
  waiter_user_id?: number | null;
  table_number?: string | null;
  status: OrderStatus;
  total_amount?: number | null; // Prisma Decimal maps to number or string, choose number for calculations
  payment_method?: string | null;
  payment_status?: string | null;
  order_type?: string | null;
  notes?: string | null;
  created_at?: Date | null;
  updated_at?: Date | null;
  // establishment: Establishment;
  // client?: User | null;
  // waiter?: User | null;
  // order_items: OrderItem[];
  // status_history: OrderStatusHistory[];
}